'use client';
import { useEffect, useRef, useState } from 'react';
import { BookOpen, Award, Newspaper, Users, GraduationCap, ClipboardList, Image as ImageIcon, Settings as SettingsIcon, Plus, Pencil, Trash2, Moon, Sun, Save, Upload, RefreshCw } from 'lucide-react';
import { translations } from '@/lib/i18n';
import { usePreferences } from '@/lib/preferences';
import { emptyText, languages, type Content, type Kind, type Lang, type RecordItem, type Settings } from '@/lib/types';
const tabs=[['news',Newspaper],['students',GraduationCap],['staff',Users],['admission',ClipboardList],['gallery',ImageIcon],['certificates',Award],['settings',SettingsIcon]] as const;
export default function Admin({userName}:{userName:string}){
 const {lang,setLang,dark,setDark}=usePreferences(),t=translations[lang];
 const [data,setData]=useState<Content|null>(null),[tab,setTab]=useState<Kind|'settings'>('news'),[editing,setEditing]=useState<RecordItem|null>(null),[editLang,setEditLang]=useState<Lang>('uz'),[settings,setSettings]=useState<Settings|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[failure,setFailure]=useState(false),[deleting,setDeleting]=useState<RecordItem|null>(null),[staffCategory,setStaffCategory]=useState('all');
 const deleteDialog=useRef<HTMLDialogElement>(null);
 const label=(k:string)=>k==='staff'?t.team:k==='settings'?t.settings:k==='certificates'?t.certificates:t[k as 'news'];
 const help=tab==='certificates'?t.certificateHelp:tab==='news'?t.newsHelp:tab==='students'?t.studentHelp:tab==='staff'?t.staffHelp:tab==='admission'?t.admissionHelp:tab==='gallery'?t.galleryHelp:t.settingsHelp;
 async function load(){try{const r=await fetch('/api/content?admin=1',{cache:'no-store'});if(!r.ok)throw new Error();const d:Content=await r.json();setData(d);setSettings(d.settings);return true;}catch{setFailure(true);setMessage(t.loadError);return false;}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 useEffect(()=>{if(deleting)deleteDialog.current?.showModal();else deleteDialog.current?.close();},[deleting]);
 function changeTab(next:Kind|'settings'){if((busy||uploading)||(dirty&&!window.confirm(t.unsaved)))return;setTab(next);setEditing(null);setSettings(data?.settings||null);setDirty(false);setMessage('');setStaffCategory('all');}
 function start(item?:RecordItem){if(busy||uploading)return;if(dirty&&!window.confirm(t.unsaved))return;setEditing(item?structuredClone(item):{id:crypto.randomUUID(),kind:tab as Kind,title:emptyText(),body:emptyText(),image:'',date:tab==='news'?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tashkent',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()):'',category:tab==='staff'?'teachers':tab==='news'?'life':'',university:emptyText(),year:'',published:false,count:tab==='certificates'?null:undefined});setEditLang(lang);setDirty(false);setMessage('');}
 function update(patch:Partial<RecordItem>){setEditing(old=>old?{...old,...patch}:old);setDirty(true);}
 async function request(payload:unknown){const r=await fetch('/api/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();return r.json();}
 async function save(){if(!editing||busy||uploading)return;setBusy(true);setMessage('');try{await request({record:editing});setDirty(false);setEditing(null);await load();setMessage(t.saved);setFailure(false);}catch{setMessage(t.saveError+' '+t.translations);setFailure(true);}finally{setBusy(false);}}
 async function saveContact(){if(!settings||busy)return;setBusy(true);setMessage('');try{await request({action:'settings',settings});setDirty(false);await load();setMessage(t.saved);setFailure(false);}catch{setMessage(t.saveError);setFailure(true);}finally{setBusy(false);}}
 async function remove(){if(!deleting||busy)return;setBusy(true);try{await request({action:'delete',id:deleting.id});setDeleting(null);await load();setMessage(t.deleteSuccess);setFailure(false);}catch{setMessage(t.saveError);setFailure(true);}finally{setBusy(false);}}
 async function upload(file:File|undefined){if(!file||!editing)return;setUploading(true);setMessage('');try{if(file.size>4*1024*1024)throw new Error();const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:fd});if(!r.ok)throw new Error();const result=await r.json() as {url:string};update({image:result.url});setFailure(false);}catch{setMessage(t.uploadError+' '+t.imageHelp);setFailure(true);}finally{setUploading(false);}}
 const records=(data?.records||[]).filter(r=>r.kind===tab&&(tab!=='staff'||staffCategory==='all'||r.category===staffCategory)).sort((a,b)=>tab==='news'?b.date.localeCompare(a.date):0);
 const contactChange=(key:keyof Settings,value:Settings[keyof Settings])=>{setSettings(old=>old?{...old,[key]:value}:old);setDirty(true);};
 return <div className="admin-shell"><header className="admin-bar"><a href="/" className="brand"><img src="/images/school-logo.png" alt={t.school} width="48" height="48"/><span><strong>{t.school}</strong><small>{t.admin}</small></span></a><a className="back-link" href="/" onClick={e=>{if(dirty&&!confirm(t.unsaved))e.preventDefault();}}>{t.back}</a><div className="nav-tools"><select value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label="Language / Til / Язык">{languages.map(l=><option key={l} value={l}>{l.toUpperCase()}</option>)}</select><button className="icon-button" aria-label={t.theme} title={t.theme} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div></header>
 <div className="admin-main"><aside className="admin-sidebar"><p>{t.dashboard}</p>{tabs.map(([key,Icon])=><button key={key} className={tab===key?'selected':''} onClick={()=>changeTab(key)} disabled={busy||uploading}><Icon size={19}/>{label(key)}</button>)}<div className="admin-user">{userName}<button type="button" onClick={async()=>{if(dirty&&!confirm(t.unsaved))return;try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw new Error();window.location.assign('/admin/login');}catch{setMessage(t.saveError);setFailure(true);}}}>{t.signout}</button></div></aside>
 <main className="admin-work"><div className="admin-heading"><div><h1>{label(tab)}</h1><p>{help}</p></div>{tab!=='settings'&&!editing&&data&&<button className="button" onClick={()=>start()}><Plus size={18}/>{t.add}</button>}</div>
 {message&&<div className={'admin-message '+(failure?'error':'')} role={failure?'alert':'status'}>{message}{!data&&<button className="admin-refresh" onClick={load}>{t.retry}</button>}</div>}
 {!data&&!message&&<div className="admin-loader">{t.loading}</div>}
 {data&&tab==='settings'&&settings&&<form className="admin-form" onSubmit={e=>{e.preventDefault();saveContact();}}><div className="language-editor">{languages.map(l=><button key={l} type="button" onClick={()=>setEditLang(l)} className={editLang===l?'selected':''}>{l.toUpperCase()}</button>)}</div><label>{t.address} ({editLang.toUpperCase()})<input value={settings.address[editLang]} onChange={e=>contactChange('address',{...settings.address,[editLang]:e.target.value})} maxLength={500}/></label><div className="form-grid"><label>{t.phone}<input type="tel" value={settings.phone} onChange={e=>contactChange('phone',e.target.value)} maxLength={80}/></label><label>{t.email}<input type="email" value={settings.email} onChange={e=>contactChange('email',e.target.value)}/></label></div>{(['telegram','instagram','youtube'] as const).map(k=><label key={k}>{k==='youtube'?'YouTube':k==='telegram'?'Telegram':'Instagram'}<input type="url" value={settings[k]} onChange={e=>contactChange(k,e.target.value)} placeholder="https://" pattern="https://.*"/></label>)}<div className="form-actions"><button className="button primary" type="submit" disabled={busy}><Save size={17}/>{busy?t.loading:t.save}</button></div></form>}
 {data&&editing&&<form className="admin-form" onSubmit={e=>{e.preventDefault();save();}}><p className="translation-note">{t.translations}</p><div className="language-editor">{languages.map(l=><button key={l} type="button" className={editLang===l?'selected':''} onClick={()=>setEditLang(l)}>{l.toUpperCase()}</button>)}</div><label>{t.title} ({editLang.toUpperCase()})<input value={editing.title[editLang]} onChange={e=>update({title:{...editing.title,[editLang]:e.target.value}})} maxLength={500} required={editing.published}/></label>{editing.kind!=='gallery'&&editing.kind!=='certificates'&&<label>{t.body} ({editLang.toUpperCase()})<textarea value={editing.body[editLang]} onChange={e=>update({body:{...editing.body,[editLang]:e.target.value}})} maxLength={20000} required={editing.published}/></label>}
 {editing.kind==='certificates'&&<label>{t.certificateCount}<input type="number" min={0} max={1000000} step={1} value={editing.count??''} onChange={e=>update({count:e.target.value===''?null:Number(e.target.value)})}/></label>}
 {editing.kind==='students'&&<div className="form-grid"><label>{t.university} ({editLang.toUpperCase()})<input value={editing.university[editLang]} onChange={e=>update({university:{...editing.university,[editLang]:e.target.value}})} maxLength={500}/></label><label>{t.year}<input value={editing.year} onChange={e=>update({year:e.target.value})} inputMode="numeric" maxLength={4}/></label></div>}
 <div className="form-grid">{(editing.kind==='news'||editing.kind==='admission')&&<label>{t.date}<input type="date" value={editing.date} onChange={e=>update({date:e.target.value})}/></label>}{(editing.kind==='news'||editing.kind==='staff')&&<label>{t.category}<select value={editing.category} onChange={e=>update({category:e.target.value})}>{(editing.kind==='news'?['science','technology','life']:['leadership','teachers','support','technical']).map(c=><option key={c} value={c}>{t[c as 'science']}</option>)}</select></label>}</div>
 {editing.kind!=='certificates'&&<div className="upload-box">{editing.image?<img src={editing.image} alt={t.image}/>:<Upload size={36}/>}<div><label>{uploading?t.loading:t.upload}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={uploading||busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label><p>{t.imageHelp}</p>{editing.image&&<button type="button" onClick={()=>update({image:''})} disabled={uploading||busy}>{t.removeImage}</button>}</div></div>}
 <label className="check-label"><input type="checkbox" checked={editing.published} onChange={e=>update({published:e.target.checked})}/>{t.published}</label><div className="form-actions"><button className="button primary" type="submit" disabled={busy||uploading}><Save size={17}/>{busy?t.loading:t.save}</button><button className="button outline" type="button" disabled={busy||uploading} onClick={()=>{if(!dirty||confirm(t.unsaved)){setEditing(null);setDirty(false);setMessage('');}}}>{t.cancel}</button></div></form>}
 {data&&tab!=='settings'&&!editing&&<>{tab==='staff'&&<div className="team-tabs">{(['all','leadership','teachers','support','technical'] as const).map(c=><button key={c} className={staffCategory===c?'selected':''} onClick={()=>setStaffCategory(c)}>{t[c]}</button>)}</div>}<p className="metadata">{records.length} {t.contentCount}</p><div className="admin-records">{records.map(r=><article key={r.id} className="admin-row">{r.image?<img src={r.image} alt={r.title[lang]}/>:<div className="row-placeholder"><BookOpen size={24}/></div>}<div className="row-copy"><h3>{r.title[lang]||'—'}</h3><p>{r.kind==='certificates'?(r.count==null?t.certificatePending:`${r.count} ${t.certificateStudents}`):r.kind==='staff'?r.body[lang]:r.date||r.year}</p><span className={'status-label '+(!r.published?'draft':'')}>{r.published?t.publishedLabel:t.draft}</span></div><div className="row-actions"><button onClick={()=>start(r)} disabled={busy}><Pencil size={15}/>{t.edit}</button><button onClick={()=>setDeleting(r)} disabled={busy}><Trash2 size={15}/>{t.delete}</button></div></article>)}{records.length===0&&<div className="empty-state">{t.empty}</div>}</div></>}
 </main></div><dialog ref={deleteDialog} className="delete-dialog" onCancel={()=>{if(!busy)setDeleting(null);}}><h2>{t.confirmDelete}</h2><p>{deleting?.title[lang]}</p><div className="form-actions"><button className="button danger" onClick={remove} disabled={busy}>{busy?t.loading:t.confirmYes}</button><button className="button outline" onClick={()=>setDeleting(null)} disabled={busy}>{t.cancel}</button></div></dialog></div>;
}
