'use client';
import { useEffect, useState } from 'react';
import { BookOpen, FlaskConical, Monitor, Trophy, BedDouble, Utensils, School as SchoolIcon, Menu, X, Moon, Sun, MapPin, Phone, Mail, Camera, Send, Play, GraduationCap, CalendarDays, ChevronDown, ExternalLink } from 'lucide-react';
import { translations } from '@/lib/i18n';
import ChemistryMotion from './chemistry-motion';
import LinkedText from './linked-text';
import MediaDialog from './media-dialog';
import CertificateStatistics from './certificate-statistics';
import { usePreferences } from '@/lib/preferences';
import { emptyText, languages, type Content, type RecordItem } from '@/lib/types';
const locale={uz:'uz-UZ',ru:'ru-RU',en:'en-GB'};
export default function School({initial,unavailable=false}:{initial:Content;unavailable?:boolean}){
 const {lang,setLang,dark,setDark}=usePreferences(),t=translations[lang];
 const [data,setData]=useState(initial),[error,setError]=useState(unavailable),[menu,setMenu]=useState(false),[active,setActive]=useState('home'),[filter,setFilter]=useState('all'),[teamFilter,setTeamFilter]=useState('leadership'),[allTeam,setAllTeam]=useState(false),[allGallery,setAllGallery]=useState(false),[selected,setSelected]=useState<RecordItem|null>(null);
 useEffect(()=>{document.title=t.schoolFull;},[lang,t.schoolFull]);
 async function refresh(){try{const r=await fetch('/api/content',{cache:'no-store'});if(!r.ok)throw new Error();setData(await r.json());setError(false);}catch{setError(true);}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,30000);const focus=()=>refresh();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);});},{rootMargin:'-20% 0px -65% 0px'});document.querySelectorAll('section[id]').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);
 const records=(kind:string)=>data.records.filter(r=>r.kind===kind&&r.published);
 const news=records('news').sort((a,b)=>b.date.localeCompare(a.date)),staff=records('staff').filter(r=>r.category===teamFilter),students=records('students'),photos=records('gallery'),admissions=records('admission');
 const links=['home','about','news','team','students','admission'] as const;
 const date=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString(locale[lang],{day:'numeric',month:'long',year:'numeric'}):'';
 const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(w=>w[0]).join('');
 useEffect(()=>{
  const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('motion-visible');observer.unobserve(entry.target);}});},{threshold:0.08});
  document.querySelectorAll('.section-heading,.news-card,.staff-card,.gallery-item,.about-images,.values > div,.admission-list article,.certificate-card,.student-photo,.student-card,.image-reveal').forEach(node=>{
   if(node.classList.contains('motion-visible'))return;
   const rect=node.getBoundingClientRect();node.classList.add('motion-prepared');
   if(rect.top<window.innerHeight&&rect.bottom>0)node.classList.add('motion-visible');else observer.observe(node);
  });
  return()=>observer.disconnect();
 },[data,filter,teamFilter,allTeam,allGallery]);
 const open=(r:RecordItem)=>setSelected(r);
 const openPhoto=(image:string,key:'lab'|'science'|'students'|'schoolFull')=>open({id:'photo-'+image,kind:'gallery',title:{uz:translations.uz[key],ru:translations.ru[key],en:translations.en[key]},body:emptyText(),image,date:'',category:'',university:emptyText(),year:'',published:true});
 return <>
  <ChemistryMotion lang={lang}/>
  <a href="#home" className="skip-link">{t.home}</a>
  <div className="utility"><div className="container"><span><MapPin size={14}/>{data.settings.address[lang]}</span><span>{t.specialized} <b>·</b> {t.branch}</span></div></div>
  <header className="header"><div className="container nav">
   <a href="#home" className="brand" onClick={()=>setMenu(false)}><img src="/images/school-logo.png" alt={t.school} width="58" height="58"/><span className="official-brand"><strong>{t.school}</strong><small>{t.schoolType}</small><b>{t.campus}</b></span></a>
   <nav className={menu?'navigation open':'navigation'} aria-label={t.navigation}>{links.map(id=><a key={id} href={'#'+id} className={active===id?'active':''} onClick={()=>setMenu(false)}>{t[id]}</a>)}</nav>
   <div className="nav-tools"><select value={lang} onChange={e=>setLang(e.target.value as typeof lang)} aria-label="Language / Til / Язык">{languages.map(l=><option key={l} value={l}>{l.toUpperCase()}</option>)}</select><button className="icon-button" title={t.theme} aria-label={t.theme} onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="icon-button menu-toggle" aria-label={t.menu} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>
  </div></header>
  {error&&<div className="load-banner" role="status">{t.loadError} <button onClick={refresh}>{t.retry}</button></div>}
  <main>
   <section className="hero" id="home">
    <div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">{t.specialized}</p><h1 aria-label={t.schoolFull}><span className="school-name">{t.school}</span><span className="school-type">{t.schoolType}</span><span className="school-campus">{t.campus}</span></h1><p className="hero-description">{t.heroText}</p><div className="hero-actions"><a className="button gold" href="#admission">{t.admissionInfo}</a><a className="button ghost" href="#about"><BookOpen size={18}/>{t.explore}</a></div></div><div className="hero-visual"><button type="button" className="photo-open hero-photo-trigger" aria-label={t.viewPhoto} onClick={()=>openPhoto('/images/095242.webp','schoolFull')}><img className="hero-photo" src="/images/095242.webp" alt={t.schoolFull}/></button><div className="hero-inset"><button type="button" className="photo-open" aria-label={t.viewPhoto} onClick={()=>openPhoto('/images/095126.webp','lab')}><img src="/images/095126.webp" alt={t.lab}/></button><span><FlaskConical size={18}/>{t.lab}</span></div><div className="hero-school-label"><BookOpen size={22}/><span><strong>{t.campus}</strong><small>{t.life}</small></span></div></div></div>
    <div className="hero-bottom school-facts"><div className="container">{[[SchoolIcon,'240',t.capacityLabel],[BedDouble,'110',t.boardingLabel],[Utensils,'5',t.mealsLabel]].map(([Icon,value,label],i)=>{const I=Icon as typeof SchoolIcon;return <a key={i} href="#about"><I size={25}/><strong>{value as string}</strong><span>{label as string}</span></a>;})}</div></div>
   </section>
   <section id="news" className="section news-section"><div className="container">
    <div className="section-heading"><div><p className="eyebrow green">{t.latest}</p><h2>{t.newsTitle}</h2></div><div className="filters">{(['all','science','technology','life'] as const).map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{t[f]}</button>)}</div></div>
    <div className="news-grid">{news.filter(n=>filter==='all'||n.category===filter).map(n=><article className="news-card" key={n.id}><button className="image-button" onClick={()=>open(n)} aria-label={n.title[lang]}>{n.image?<img src={n.image} alt={n.title[lang]} loading="lazy"/>:<div className="no-image"><BookOpen size={42}/></div>}<span className="image-category">{t[n.category as 'science']||t.news}</span></button><div className="news-card-copy">{n.date&&<p className="metadata"><CalendarDays size={14}/>{date(n.date)}</p>}<h3><button onClick={()=>open(n)}>{n.title[lang]}</button></h3><p>{n.body[lang]}</p><button className="text-button" onClick={()=>open(n)}>{t.read}<span className="small-line"/></button></div></article>)}</div>
    {!news.filter(n=>filter==='all'||n.category===filter).length&&<p className="empty-state">{t.empty}</p>}
   </div></section>
   <section id="about" className="section about-section"><div className="container about-grid"><div className="about-images"><button type="button" className="photo-open about-main-trigger" aria-label={t.viewPhoto} onClick={()=>openPhoto('/images/095126.webp','lab')}><img className="about-main" src="/images/095126.webp" alt={t.lab} loading="lazy"/></button><button type="button" className="photo-open about-small-trigger" aria-label={t.viewPhoto} onClick={()=>openPhoto('/images/095140.webp','science')}><img className="about-small" src="/images/095140.webp" alt={t.science} loading="lazy"/></button><span className="about-caption"><FlaskConical size={22}/>{t.lab}</span></div><div><p className="eyebrow green">{t.aboutTop}</p><h2>{t.aboutTitle}</h2><p className="section-intro">{t.aboutText}</p><div className="values">{[[BedDouble,t.dormitory,t.dormitoryText],[Utensils,t.meals,t.mealsText],[SchoolIcon,t.classrooms,t.classroomsText]].map(([Icon,title,text],i)=>{const I=Icon as typeof FlaskConical;return <div key={i}><span className="value-icon"><I size={22}/></span><div><h3>{title as string}</h3><p>{text as string}</p></div></div>;})}</div><div className="preparation-courses"><h3>{t.preparationTitle}</h3><div className="course-tags">{[t.biology,t.chemistry,t.englishSubject,t.mathematics,t.uzbekSubject,t.physics].map(subject=><span key={subject}>{subject}</span>)}</div><p>{t.preparationText}</p></div></div></div></section>
   <section id="team" className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow green">{t.teamTop}</p><h2>{t.teamTitle}</h2><p className="section-intro">{t.teamText}</p></div></div><div className="team-tabs">{(['leadership','teachers','support','technical'] as const).map(f=><button key={f} className={teamFilter===f?'selected':''} onClick={()=>{setTeamFilter(f);setAllTeam(false);}}>{t[f]}<small>{records('staff').filter(r=>r.category===f).length}</small></button>)}</div><div className="staff-grid">{staff.slice(0,allTeam?staff.length:6).map((s,i)=><article className="staff-card" key={s.id}><button type="button" aria-label={s.title[lang]} onClick={()=>open(s)} className={'staff-photo tone-'+(i%3)}>{s.image?<img src={s.image} alt={s.title[lang]} loading="lazy"/>:<><span className="initials">{initials(s.title[lang])}</span><span className="avatar-decoration"><BookOpen size={27}/></span></>}</button><div className="staff-info"><p className="staff-role">{s.body[lang]}</p><h3>{s.title[lang]}</h3></div></article>)}</div>{staff.length>6&&<div className="center"><button className="button outline" onClick={()=>setAllTeam(!allTeam)}>{allTeam?t.less:t.more}<ChevronDown size={16} className={allTeam?'rotated':''}/></button></div>}</div></section>
   <section id="students" className="students-section"><div className="container students-intro"><div className="student-photo"><button type="button" className="photo-open student-photo-trigger" aria-label={t.viewPhoto} onClick={()=>openPhoto('/images/095149.webp','students')}><img src="/images/095149.webp" alt={t.students} loading="lazy"/></button><span className="photo-label"><GraduationCap/>{t.studentTop}</span></div><div><p className="eyebrow">{t.studentTop}</p><h2>{t.studentTitle}</h2><p className="section-intro">{t.studentText}</p>{!students.length&&<div className="alumni-empty"><GraduationCap size={30}/><p>{t.studentEmpty}</p></div>}</div></div>{students.length>0&&<div className="container student-grid">{students.map(s=><article className="student-card" key={s.id}>{s.image?<button type="button" className="photo-open student-portrait" aria-label={s.title[lang]} onClick={()=>open(s)}><img src={s.image} alt={s.title[lang]} loading="lazy"/></button>:<div className="student-avatar">{initials(s.title[lang])}</div>}<div>{s.year&&<p className="metadata">{t.year}: {s.year}</p>}<h3>{s.title[lang]}</h3>{s.university[lang]&&<h4><GraduationCap size={18}/>{s.university[lang]}</h4>}<p className="preserve-lines">{s.body[lang]}</p></div></article>)}</div>}</section>
   <CertificateStatistics records={records('certificates')} lang={lang}/>
   <section id="admission" className="section admission-section"><div className="container admission-grid"><div><p className="eyebrow green">{t.admissionTop}</p><h2>{t.admissionTitle}</h2><button type="button" className="photo-open image-reveal admission-photo-trigger" aria-label={t.viewPhoto} onClick={()=>openPhoto('/images/095257.webp','schoolFull')}><img src="/images/095257.webp" alt={t.schoolFull} loading="lazy"/></button></div><div className="admission-list">{admissions.map((a,i)=><article key={a.id}><span className="admission-number">{String(i+1).padStart(2,'0')}</span><div>{a.date&&<p className="metadata">{date(a.date)}</p>}<h3>{a.title[lang]}</h3><p className="preserve-lines"><LinkedText text={a.body[lang]}/></p>{a.image&&<button type="button" className="photo-open" aria-label={a.title[lang]} onClick={()=>open(a)}><img className="admission-image" src={a.image} alt={a.title[lang]} loading="lazy"/></button>}</div></article>)}{!admissions.length&&<p className="empty-state">{t.empty}</p>}</div></div></section>
   <section id="gallery" className="section gallery-section"><div className="container"><div className="section-heading"><div><p className="eyebrow green">{t.galleryTop}</p><h2>{t.galleryTitle}</h2></div><span className="gallery-count">{String(photos.length).padStart(2,'0')} <span>{t.gallery.toLowerCase()}</span></span></div><div className="gallery-grid">{photos.slice(0,allGallery?photos.length:6).map((p,i)=><button key={p.id} className={'gallery-item gallery-'+(i%6)} onClick={()=>open(p)} aria-label={p.title[lang]}><img src={p.image} alt={p.title[lang]} loading="lazy"/><span>{p.title[lang]}<ExternalLink size={17}/></span></button>)}</div>{photos.length>6&&<div className="center"><button className="button outline" onClick={()=>setAllGallery(!allGallery)}>{allGallery?t.less:t.more}<ChevronDown size={16}/></button></div>}</div></section>
  </main>
  <footer id="contact"><div className="container footer-grid"><div className="footer-brand"><a className="brand" href="#home"><img src="/images/school-logo.png" alt={t.school} width="64" height="64"/><span className="official-brand"><strong>{t.school}</strong><small>{t.schoolType}</small><b>{t.campus}</b></span></a><p className="footer-official-name">{t.schoolFull}</p><p>{t.footerText}</p></div><div><h3>{t.navigation}</h3>{(['about','news','team','students','certificates','admission','gallery'] as const).map(k=><a href={'#'+k} key={k}>{t[k]}</a>)}</div><div className="footer-contact"><h3>{t.contact}</h3><p><MapPin size={18}/>{data.settings.address[lang]}</p>{data.settings.phone&&<a href={'tel:'+data.settings.phone.replace(/[^+\d]/g,'')}><Phone size={17}/>{data.settings.phone}</a>}{data.settings.email&&<a href={'mailto:'+data.settings.email}><Mail size={17}/>{data.settings.email}</a>}</div><div><h3>{t.social}</h3><div className="social-links">{[[Send,'telegram','Telegram'],[Camera,'instagram','Instagram'],[Play,'youtube','YouTube']].map(([Icon,key,label])=>{const I=Icon as typeof Send,url=data.settings[key as 'telegram'];return url?<a href={url} key={key as string} target="_blank" rel="noopener noreferrer"><I size={18}/>{label as string}</a>:null;})}</div>{!data.settings.telegram&&!data.settings.instagram&&!data.settings.youtube&&<p className="social-empty">{t.socialEmpty}</p>}</div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} {t.school}. {t.rights}</p><p className="developer-credit">{t.developer}: <a href="https://t.me/Ziyovuddin02" target="_blank" rel="noopener noreferrer">Bekmuratov Ziyovuddin</a></p><a href="/admin">{t.admin}</a></div></footer>
  <MediaDialog selected={selected} photos={photos} lang={lang} onSelect={setSelected} onDismiss={()=>setSelected(null)}/>
 </>;
}
