export const schoolInformation = {
  "uz": {
    "heroText": "Biologiya, kimyo, fizika va ingliz tili chuqurlashtirib o‘qitiladigan tabiiy fanlar yo‘nalishidagi maktab. Toshkent viloyati o‘quvchilari 7-sinfdan boshlab tanlov asosida qabul qilinadi.",
    "aboutTitle": "Ta’lim va yashash uchun yaratilgan sharoitlar.",
    "aboutText": "Maktab 240 nafar o‘quvchiga mo‘ljallangan. Olis hududlardan kelgan o‘quvchilar uchun 110 o‘rinli zamonaviy yotoqxona mavjud. Ta’lim zamonaviy metodlar asosida olib borilib, o‘quvchilar respublika va xalqaro fan olimpiadalariga tayyorlanadi.",
    "dormitory": "110 o‘rinli yotoqxona",
    "dormitoryText": "Olis hududlardan kelgan o‘quvchilar uchun zamonaviy yashash sharoitlari.",
    "meals": "Kuniga 5 mahal ovqatlanish",
    "mealsText": "O‘quvchilar uchun kuniga 5 mahal sog‘lom ovqatlanish tashkil etilgan.",
    "classrooms": "Zamonaviy sinfxonalar",
    "classroomsText": "Barcha sinfxonalar zamonaviy jihozlar bilan ta’minlangan.",
    "capacityLabel": "O‘quvchi uchun mo‘ljallangan",
    "boardingLabel": "Yotoqxona o‘rni",
    "mealsLabel": "Mahal sog‘lom ovqatlanish",
    "preparationTitle": "Bepul tayyorlov kurslari",
    "preparationText": "Mashg‘ulotlar malakali, sertifikatga ega ustozlar tomonidan olib boriladi.",
    "biology": "Biologiya",
    "chemistry": "Kimyo",
    "englishSubject": "Ingliz tili",
    "mathematics": "Matematika",
    "uzbekSubject": "Ona tili",
    "physics": "Fizika",
    "labText": "Kimyo va biologiya laboratoriyalarida amaliy mashg‘ulotlar.",
    "itText": "Zamonaviy jihozlangan sinfxonalarda informatika mashg‘ulotlari.",
    "sportText": "O‘quvchilarning jismoniy faolligi uchun sport mashg‘ulotlari.",
    "teamText": "Darslar malakali, sertifikatga ega ustozlar tomonidan olib boriladi.",
    "admissionTop": "QABUL BO‘YICHA MA’LUMOT",
    "admissionTitle": "7-sinfga qabul",
    "footerText": "Maqsadimiz — bilimli, yetuk va jamiyatga foydali yoshlarni tarbiyalash.",
    "certificates": "Milliy sertifikatlar",
    "certificateEyebrow": "O‘quvchilarimiz natijalari",
    "certificateStudents": "nafar sertifikat olgan o‘quvchi",
    "certificatePending": "Ma’lumot kutilmoqda",
    "certificateCount": "Sertifikat olgan o‘quvchilar soni",
    "certificateHelp": "Har bir fan bo‘yicha sertifikat olgan o‘quvchilar sonini kiriting. Yangi fan qo‘shish, sonni o‘zgartirish va nashr holatini boshqarish mumkin. Son bo‘sh qolsa, saytda ma’lumot kutilayotganini bildiradi.",
    "developer": "Dasturchi",
    "previousPhoto": "Oldingi rasm",
    "nextPhoto": "Keyingi rasm",
    "imageUnavailable": "Rasmni yuklab bo‘lmadi.",
    "viewPhoto": "Rasmni kattalashtirish"
  },
  "ru": {
    "heroText": "Школа естественно-научного направления с углублённым изучением биологии, химии, физики и английского языка. Ученики из Ташкентской области принимаются по конкурсу начиная с 7-го класса.",
    "aboutTitle": "Условия для обучения и проживания.",
    "aboutText": "Школа рассчитана на 240 учеников. Для детей из отдалённых районов предусмотрено современное общежитие на 110 мест. Обучение ведётся по современным методикам; ученики готовятся к республиканским и международным предметным олимпиадам.",
    "dormitory": "Общежитие на 110 мест",
    "dormitoryText": "Современные условия проживания для учеников из отдалённых районов.",
    "meals": "Пятиразовое питание",
    "mealsText": "Для учеников организовано пятиразовое здоровое питание.",
    "classrooms": "Современные классы",
    "classroomsText": "Все классы оснащены современным оборудованием.",
    "capacityLabel": "Вместимость школы",
    "boardingLabel": "Мест в общежитии",
    "mealsLabel": "Приёмов пищи в день",
    "preparationTitle": "Бесплатные подготовительные курсы",
    "preparationText": "Занятия проводят квалифицированные преподаватели, имеющие сертификаты.",
    "biology": "Биология",
    "chemistry": "Химия",
    "englishSubject": "Английский язык",
    "mathematics": "Математика",
    "uzbekSubject": "Родной язык",
    "physics": "Физика",
    "labText": "Практические занятия в лабораториях химии и биологии.",
    "itText": "Занятия информатикой в современных оборудованных классах.",
    "sportText": "Спортивные занятия для физического развития учеников.",
    "teamText": "Занятия проводят квалифицированные преподаватели, имеющие сертификаты.",
    "admissionTop": "ИНФОРМАЦИЯ О ПРИЁМЕ",
    "admissionTitle": "Приём в 7-й класс",
    "footerText": "Наша цель — воспитывать образованных, зрелых молодых людей, полезных обществу.",
    "certificates": "Национальные сертификаты",
    "certificateEyebrow": "Результаты наших учеников",
    "certificateStudents": "учеников получили сертификат",
    "certificatePending": "Данные ожидаются",
    "certificateCount": "Число учеников с сертификатом",
    "certificateHelp": "Укажите число учеников с сертификатом по каждому предмету. Можно добавлять предметы, менять число и управлять публикацией. Пустое поле означает, что данные ожидаются.",
    "developer": "Разработчик",
    "previousPhoto": "Предыдущее фото",
    "nextPhoto": "Следующее фото",
    "imageUnavailable": "Не удалось загрузить изображение.",
    "viewPhoto": "Увеличить фото"
  },
  "en": {
    "heroText": "A science-focused school offering advanced study in biology, chemistry, physics and English. Students from Tashkent region are admitted through competitive selection from Grade 7.",
    "aboutTitle": "Facilities for learning and school life.",
    "aboutText": "The school accommodates 240 students. A modern 110-place boarding facility is available for students from remote areas. Modern teaching methods support preparation for national and international subject Olympiads.",
    "dormitory": "110-place boarding facility",
    "dormitoryText": "Modern accommodation for students from remote areas.",
    "meals": "Five meals a day",
    "mealsText": "Students receive five healthy meals each day.",
    "classrooms": "Modern classrooms",
    "classroomsText": "Every classroom is equipped with modern learning facilities.",
    "capacityLabel": "Student capacity",
    "boardingLabel": "Boarding places",
    "mealsLabel": "Healthy meals daily",
    "preparationTitle": "Free preparatory courses",
    "preparationText": "Classes are taught by qualified, certified teachers.",
    "biology": "Biology",
    "chemistry": "Chemistry",
    "englishSubject": "English",
    "mathematics": "Mathematics",
    "uzbekSubject": "Uzbek language",
    "physics": "Physics",
    "labText": "Practical classes in chemistry and biology laboratories.",
    "itText": "Computer science lessons in modern, equipped classrooms.",
    "sportText": "Sports activities supporting students’ physical development.",
    "teamText": "Lessons are taught by qualified, certified teachers.",
    "admissionTop": "ADMISSIONS INFORMATION",
    "admissionTitle": "Grade 7 admissions",
    "footerText": "Our aim is to educate knowledgeable, mature young people who contribute to society.",
    "certificates": "National certificates",
    "certificateEyebrow": "Our students’ achievements",
    "certificateStudents": "students earned a certificate",
    "certificatePending": "Awaiting data",
    "certificateCount": "Students with a certificate",
    "certificateHelp": "Enter the number of certificate holders for each subject. Add subjects, update counts and manage publication. Leave the count blank while awaiting data.",
    "developer": "Developer",
    "previousPhoto": "Previous photo",
    "nextPhoto": "Next photo",
    "imageUnavailable": "Unable to load this image.",
    "viewPhoto": "Enlarge photo"
  }
};
